// Canonical ingredient dictionary, seeded into the `Ingredient` table.
// Each entry is a canonical name or [canonical, ...aliases]. Names are matched
// after lowercasing and singularizing, so list singular forms.
// Categories double as store sections for future shopping lists.
// Curate this file to improve matching; re-run `prisma db seed` to apply.

type Entry = string | [string, ...string[]];

export const INGREDIENT_GROUPS: Record<string, Entry[]> = {
  produce: [
    ["onion", "yellow onion", "white onion", "brown onion"],
    "red onion",
    ["green onion", "scallion", "spring onion"],
    "shallot",
    "garlic",
    "ginger",
    "lemongrass",
    [
      "bell pepper",
      "red bell pepper",
      "green bell pepper",
      "yellow bell pepper",
      "orange bell pepper",
      "sweet pepper",
    ],
    ["jalapeño", "jalapeno"],
    ["chile pepper", "chili pepper", "thai chili", "serrano pepper", "fresno chile"],
    ["poblano pepper", "poblano"],
    "tomato",
    ["cherry tomato", "grape tomato"],
    "potato",
    ["sweet potato", "yam"],
    "carrot",
    "celery",
    "cucumber",
    "zucchini",
    ["squash", "yellow squash", "summer squash"],
    "butternut squash",
    "pumpkin",
    "eggplant",
    "broccoli",
    "cauliflower",
    ["cabbage", "green cabbage", "napa cabbage"],
    "red cabbage",
    ["bok choy", "baby bok choy"],
    ["spinach", "baby spinach"],
    "kale",
    ["lettuce", "romaine", "romaine lettuce", "iceberg lettuce"],
    "arugula",
    "mushroom",
    ["shiitake mushroom", "shiitake"],
    ["cremini mushroom", "cremini", "baby bella"],
    ["corn", "sweet corn", "corn kernel"],
    ["pea", "green pea", "frozen pea"],
    ["green bean", "string bean"],
    "asparagus",
    "brussels sprout",
    "leek",
    "fennel",
    "radish",
    "beet",
    "avocado",
    "lemon",
    "lime",
    "orange",
    "apple",
    "banana",
    "mango",
    "pineapple",
    "strawberry",
    "blueberry",
    "raspberry",
    "peach",
    "pear",
    "grape",
    "cilantro",
    ["parsley", "flat-leaf parsley", "italian parsley"],
    "basil",
    ["thai basil", "holy basil"],
    "mint",
    "dill",
    "chive",
    "rosemary",
    "thyme",
    "sage",
    "oregano",
    "bean sprout",
    ["tomatillo"],
  ],
  "meat & seafood": [
    ["chicken breast", "boneless skinless chicken breast"],
    ["chicken thigh", "boneless skinless chicken thigh", "bone-in chicken thigh"],
    ["chicken", "whole chicken", "chicken wing", "chicken drumstick"],
    ["ground chicken"],
    ["ground beef", "minced beef", "lean ground beef"],
    ["beef", "steak", "flank steak", "sirloin", "ribeye", "beef chuck", "chuck roast", "short rib"],
    ["ground pork", "minced pork"],
    ["pork", "pork shoulder", "pork belly", "pork loin", "pork chop", "pork tenderloin"],
    ["ground turkey"],
    ["turkey", "turkey breast"],
    ["lamb", "ground lamb"],
    "bacon",
    ["sausage", "italian sausage", "chorizo", "kielbasa"],
    ["ham", "prosciutto"],
    ["shrimp", "prawn"],
    "salmon",
    ["white fish", "cod", "tilapia", "halibut", "haddock"],
    "tuna",
    ["scallop", "sea scallop"],
    ["clam", "mussel"],
    "anchovy",
  ],
  "dairy & eggs": [
    ["egg", "egg yolk", "egg white"],
    ["butter", "unsalted butter", "salted butter"],
    ["milk", "whole milk", "2% milk"],
    ["heavy cream", "heavy whipping cream", "whipping cream", "double cream"],
    "half and half",
    ["sour cream", "crème fraîche", "creme fraiche"],
    ["yogurt", "greek yogurt", "plain yogurt"],
    "buttermilk",
    "cream cheese",
    ["parmesan", "parmesan cheese", "parmigiano reggiano", "grated parmesan"],
    ["mozzarella", "mozzarella cheese", "fresh mozzarella"],
    ["cheddar", "cheddar cheese", "sharp cheddar"],
    ["feta", "feta cheese"],
    ["ricotta", "ricotta cheese"],
    ["goat cheese", "chèvre"],
    ["pecorino", "pecorino romano"],
    ["gruyère", "gruyere"],
    ["monterey jack", "pepper jack"],
    ["cheese", "shredded cheese"],
  ],
  "grains & pasta": [
    [
      "rice",
      "white rice",
      "jasmine rice",
      "basmati rice",
      "long-grain rice",
      "short-grain rice",
      "sushi rice",
    ],
    "brown rice",
    [
      "pasta",
      "spaghetti",
      "penne",
      "rigatoni",
      "fettuccine",
      "linguine",
      "macaroni",
      "orzo",
      "lasagna noodle",
      "lasagna sheet",
      "bucatini",
      "orecchiette",
      "farfalle",
    ],
    [
      "noodle",
      "egg noodle",
      "ramen noodle",
      "udon noodle",
      "soba noodle",
      "rice noodle",
      "rice vermicelli",
    ],
    ["quinoa"],
    ["couscous"],
    ["oat", "rolled oat", "old-fashioned oat"],
    ["bread", "sourdough bread", "baguette", "ciabatta"],
    ["breadcrumb", "panko", "panko breadcrumb"],
    ["tortilla", "flour tortilla", "corn tortilla"],
    ["pita", "naan", "flatbread"],
    ["gnocchi"],
  ],
  baking: [
    ["all-purpose flour", "flour", "plain flour", "ap flour"],
    ["bread flour"],
    ["whole wheat flour"],
    ["cornstarch", "corn starch", "cornflour"],
    ["baking powder"],
    ["baking soda", "bicarbonate of soda"],
    ["yeast", "active dry yeast", "instant yeast"],
    ["sugar", "granulated sugar", "white sugar", "caster sugar"],
    ["brown sugar", "light brown sugar", "dark brown sugar"],
    ["powdered sugar", "confectioners sugar", "icing sugar"],
    ["honey"],
    ["maple syrup"],
    ["vanilla extract", "vanilla", "pure vanilla extract"],
    ["chocolate", "dark chocolate", "semisweet chocolate", "chocolate chip"],
    ["cocoa powder", "unsweetened cocoa powder"],
    ["cornmeal", "polenta"],
    ["tapioca starch", "tapioca flour"],
    ["gelatin"],
  ],
  pantry: [
    ["olive oil", "extra virgin olive oil", "extra-virgin olive oil"],
    [
      "vegetable oil",
      "neutral oil",
      "cooking oil",
      "canola oil",
      "avocado oil",
      "sunflower oil",
      "grapeseed oil",
    ],
    ["hominy", "white hominy", "yellow hominy"],
    ["dashi", "dashi stock", "dashi powder", "hondashi"],
    ["curry roux", "japanese curry roux"],
    ["sesame oil", "toasted sesame oil"],
    ["coconut milk", "coconut cream", "full-fat coconut milk"],
    ["chicken stock", "chicken broth"],
    ["beef stock", "beef broth"],
    ["vegetable stock", "vegetable broth"],
    ["stock", "broth", "bone broth"],
    [
      "diced tomato",
      "canned tomato",
      "crushed tomato",
      "whole peeled tomato",
      "san marzano tomato",
    ],
    ["tomato paste"],
    ["tomato sauce", "passata", "marinara sauce"],
    ["black bean"],
    ["chickpea", "garbanzo bean"],
    ["kidney bean", "red kidney bean"],
    ["white bean", "cannellini bean", "navy bean", "great northern bean"],
    ["pinto bean"],
    ["lentil", "red lentil", "green lentil"],
    ["tofu", "firm tofu", "extra-firm tofu", "silken tofu"],
    ["peanut butter"],
    ["tahini"],
    ["raisin"],
    ["dried cranberry"],
    ["coconut", "shredded coconut", "desiccated coconut"],
    ["water"],
    ["wine", "white wine", "dry white wine", "red wine", "dry red wine"],
    ["mirin"],
    ["sake", "shaoxing wine", "rice wine", "cooking wine"],
    ["beer"],
  ],
  "condiments & sauces": [
    ["soy sauce", "light soy sauce", "low-sodium soy sauce", "tamari", "shoyu"],
    ["dark soy sauce"],
    ["fish sauce"],
    ["oyster sauce"],
    ["hoisin sauce", "hoisin"],
    ["sriracha"],
    ["gochujang"],
    ["hot sauce"],
    ["chili crisp", "chili oil", "chili garlic sauce"],
    ["worcestershire sauce", "worcestershire"],
    ["ketchup"],
    ["mayonnaise", "mayo", "kewpie mayo"],
    ["mustard", "dijon mustard", "whole grain mustard", "yellow mustard"],
    ["vinegar", "white vinegar", "distilled vinegar"],
    ["rice vinegar", "rice wine vinegar", "seasoned rice vinegar"],
    ["apple cider vinegar"],
    ["balsamic vinegar", "balsamic"],
    ["red wine vinegar", "white wine vinegar", "sherry vinegar"],
    ["miso", "white miso", "miso paste"],
    ["pesto"],
    ["salsa"],
    ["curry paste", "red curry paste", "green curry paste"],
    ["harissa"],
    ["chili paste", "calabrian chili paste", "sambal oelek"],
    ["fukujinzuke", "pickled vegetable"],
    ["capers"],
    ["olive", "kalamata olive", "green olive"],
    ["pickle"],
  ],
  spices: [
    ["salt", "kosher salt", "sea salt", "table salt", "flaky salt"],
    ["black pepper", "pepper", "ground black pepper", "freshly ground black pepper"],
    ["red pepper flakes", "crushed red pepper", "chili flakes"],
    ["cumin", "ground cumin", "cumin seed"],
    ["coriander", "ground coriander", "coriander seed"],
    ["paprika", "sweet paprika"],
    ["smoked paprika"],
    ["chili powder"],
    ["cayenne", "cayenne pepper"],
    ["turmeric", "ground turmeric"],
    ["cinnamon", "ground cinnamon", "cinnamon stick"],
    ["nutmeg", "ground nutmeg"],
    ["garlic powder"],
    ["onion powder"],
    ["dried oregano"],
    ["dried thyme"],
    ["italian seasoning"],
    ["bay leaf"],
    ["curry powder"],
    ["garam masala"],
    ["five spice", "chinese five spice"],
    ["star anise"],
    ["cardamom", "ground cardamom"],
    ["clove", "ground clove"],
    ["allspice"],
    ["ginger powder", "ground ginger"],
    ["msg"],
    ["white pepper"],
    ["sichuan peppercorn"],
    ["everything bagel seasoning"],
    ["saffron"],
    ["shichimi togarashi", "togarashi"],
  ],
  "nuts & seeds": [
    ["sesame seed", "toasted sesame seed", "white sesame seed", "black sesame seed"],
    ["peanut", "roasted peanut"],
    ["almond", "sliced almond", "slivered almond"],
    ["walnut"],
    ["pecan"],
    ["cashew"],
    ["pine nut"],
    ["pistachio"],
    ["chia seed"],
    ["flaxseed", "ground flaxseed"],
    ["pumpkin seed", "pepita"],
  ],
  frozen: [
    ["frozen mixed vegetable", "stir fry vegetable", "stir fry veggie", "mixed vegetable"],
    ["frozen spinach"],
    ["frozen corn"],
    ["puff pastry"],
    ["pie crust", "pie dough"],
  ],
};

export interface IngredientSeed {
  name: string;
  aliases: string[];
  category: string;
}

export const INGREDIENTS: IngredientSeed[] = Object.entries(INGREDIENT_GROUPS).flatMap(
  ([category, entries]) =>
    entries.map((entry) => {
      const [name, ...aliases] = typeof entry === "string" ? [entry] : entry;
      return { name, aliases, category };
    })
);
